# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-22 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import tracker.apps.track.models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='location',
            field=models.CharField(max_length=50, validators=[tracker.apps.track.models.validate_lat_long]),
        ),
    ]
